export const navItems = {
    'Computers': {
        'submenu': [
            { label: 'Моноблоки' },
            { label: 'Компьютеры' },
            { label: 'Системные блоки' },
            { label: 'Микрокомпьютеры' },
            { label: 'Игровые компьютеры' },
        ],
        'image': 'image.png',
        'menubgcolor': 'deepskyblue',
        'bgcolor': 'hotpink',
    },
    'Notebooks': {
        'submenu': [
            { label: 'Недорогие ноутбуки' },
            { label: 'Игровые ноутбуки' },
            { label: 'Ультрабуки' },
            { label: 'Ноутбуки-трансформеры' },
            { label: 'Ноутбуки Huawei' },
            { label: 'Ноутбуки MSI' },
            { label: 'Ноутбуки Apple' },
        ],
        'image': 'image.png',
        'menubgcolor': 'coral',
        'bgcolor': 'brown',
    },
    'Monitors': {
        'submenu': [
            { label: 'Игровые мониторы' },
            { label: 'Мониторы 27 дюймов' },
            { label: 'Мониторы 24 дюйма' },
            { label: '4K мониторы' },
            { label: '2K мониторы' },
            { label: 'Мониторы IPS' },
            { label: 'Изогнутые мониторы' },
            { label: 'LED панели' },
        ],
        'image': 'image.png',
        'menubgcolor': 'aquamarine',
        'bgcolor': 'crimson',
    },
    'Storages': {
        'submenu': [
            { label: 'Сетевые хранилища NAS' },
            { label: 'Флешки' },
            { label: 'Внешние диски' },
            { label: 'Карты памяти' },
            { label: 'Картридеры' },
            { label: 'Оптические диски' },
        ],
        'image': 'image.png',
        'menubgcolor': 'beige',
        'bgcolor': 'deepskyblue',
    },
    'UPs': {
        'submenu': [
            { label: 'Сетевые разветвители' },
            { label: 'Сетевые удлинители' },
            { label: 'Сетевые фильтры' },
            { label: 'Источники бесперебойного питания' },
            { label: 'Сетевые фильтры и удлинители' },
        ],
        'image': 'image.png',
        'menubgcolor': 'thistle',
        'bgcolor': 'teal',
    },
    'Printers': {
        'submenu': [
            { label: 'Принтеры' },
            { label: 'Плоттеры' },
            { label: 'Копиры' },
            { label: 'Проекторы' },
            { label: 'МФУ' },
            { label: 'Картриджи' },
            { label: 'Тонеры' },
            { label: 'Фотобарабаны' },
            { label: 'Бумага' },
            { label: 'Термопленки' },
        ],
        'image': 'image.png',
        'menubgcolor': 'yellowgreen',
        'bgcolor': 'coral',
    },
    'Accesories': {
        'submenu': [
            { label: 'Сетевое оборудование' },
            { label: 'Колонки для компьютера' },
            { label: 'Bluetooth адаптеры' },
            { label: 'Powerline адаптеры' },
            { label: 'Wi-Fi адаптеры' },
            { label: 'Операционные системы' },
            { label: 'Офисные приложения' },
            { label: 'Антивирусы' },
            { label: 'Утилиты' },
        ],
        'image': 'image.png',
        'menubgcolor': 'beige',
        'bgcolor': 'violet',
    },
};

export type Slug = keyof typeof navItems;
